language: node_js
node_js: 'node'
addons:
  code_climate:
    repo_token: 3be91b314d261c9033897d399ae2e92baf03469103ea49ee0c05feb1fb8aeb72
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
